### ISSUE TITLE
Code / weights for market1501 and CUHK03 

### ISSUE THREAD

**Issue by Shamazo** [ggjy/P2Net.pytorch#2]
Hi,

I know you said you would add to the repo, but I wanted to ask if you were planning to release the weights for the model trained on market1501 and/or CUHK03? I am interested in playing around with your model, but I do not have access to the Duke dataset since it has been withdrawn and the website is down. 

Thank you

**Comment by ggjy** [comment]
Yes, I will release both the code and weights on Market-1501 and CUHK03.
