### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by td9020** [ggjy/P2Net.pytorch#3]
Hi,
while run your code on the colab, i got the following error

Traceback (most recent call last):
  File "train_duke.py", line 414, in <module>
    model = train_model(model, optimizer, None, num_epochs=opt.epoch)
  File "train_duke.py", line 239, in train_model
    [category, feature, pool5,_] = model(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/P2Net.pytorch/model.py", line 111, in forward
    x = self.context_l2_1(x, part_map)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

P.S: I downloaded train_list.txt file from here  https://raw.githubusercontent.com/sxzrt/DukeMTMC-reID_evaluation/master/train_list.txt

**Comment by lanyin196** [comment]
I also meet this question....
how do you solve this problem finally?can you tell me ?

**Comment by ggjy** [comment]
The default setting is using part_map. Do you choose to not use the part_map? I suggest you to check the input.shape in File "train_duke.py", line 239.

**Comment by td9020** [comment]
now i am using part_map, i got the same error.
and for inputs.shape i got this   "torch.Size([48, 3, 384, 128])"

**Comment by td9020** [comment]
If I change 
`         x = self.context_l2_1(x, part_map) `

to 
`        x = self.context_l2_1(x)`

I don't get the above error. But I am not sure if this is right and what the consequences of the changes are.  @ggjy can you help?

**Comment by ggjy** [comment]
@thohtdelta Do you set the BLOCK_NUM=1 in the scripts ?
`        x = self.context_l2_1(x)` means the baseline module or only add latent branch.
`         x = self.context_l2_1(x, part_map) ` means the human part branch and latent branch.
You can refer to the code at 
https://github.com/ggjy/P2Net.pytorch/blob/master/model.py#L82
and
https://github.com/ggjy/P2Net.pytorch/blob/master/blocks/ms_non_local_block.py#L186
I guess you set the BLOCK_NUM=0 (default)

**Comment by OxInsky** [comment]
> If I change
>         x = self.context_l2_1(x, part_map)
> to
>         x = self.context_l2_1(x)
> I don't get the above error. But I am not sure if this is right and what the consequences of the changes are.  @ggjy can you help?

excuse me,can you tell me if you have solved this problem?

**Comment by zongzhesun** [comment]
I also meet this problem
Traceback (most recent call last):
  File "train_duke.py", line 413, in <module>
    model = train_model(model, optimizer, None, num_epochs=opt.epoch)
  File "train_duke.py", line 236, in train_model
    [category, feature, pool5, embed] = model(inputs, part_map=part_map, path=inputs_ori)
  File "C:\Anocoda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Project\P2Net.pytorch-master\model.py", line 111, in forward
    x = self.context_l2_1(x, part_map)
  File "C:\Anocoda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

Please tell me if you have solved this problem?

**Comment by ggjy** [comment]
The nn.Sequential() can't take x, pmap as input, I have fixed this bug.
