### ISSUE TITLE
triplet_dataset

### ISSUE THREAD

**Issue by CharlesJames13586** [ggjy/P2Net.pytorch#5]
你好，train_duke中93行triplet_dataset，代码标红，我想问下这个数据集具体是什么？谢谢了！

**Comment by ggjy** [comment]
我们除了用Cross entropy loss之外还用了triplet loss，需要输入为三元组，所以要重新利用RandomIdentitySampler去采样三元组，93行的triplet_dataset其实没有特别的，和cls_dataset其实一样
