### ISSUE TITLE
自注意模块中的两个参数vis,if_gc

### ISSUE THREAD

**Issue by CharlesJames13586** [ggjy/P2Net.pytorch#7]
你好，我在看你的代码时又有了新的疑惑，在P2网络中间有部分使用到了自注意机制，后来我又去看了《Non-local Neural Networks》，但是对ms_non_local_block.py中MSPyramidAttentionContextModule中的if_gc参数和_MS_NonLocalBlockND中的vis参数不理解，不知道这俩是用来做什么的，而且好像也没有看到代码中使用了vis参数。先在此提前谢谢您的回复。（顺祝科研愉快）

**Comment by ggjy** [comment]
vis是用来可视化的，if_gc是其他ablation study用的接口，没删得太细
